import type { Labels } from './types';

export const en: Labels = {
  brand: 'Backlog Palette',
  palette: {
    inputLabel: 'Search',
    placeholder: 'Type a page name or issue key',
    listLabel: 'Suggestions',
    escClose: 'Close',
    escBack: 'Back',
    armedNotice: (segment) => `Again to remove ${segment}`,
    rootScope: 'Spaces',
    rootPlaceholder: 'Pick a space to go to',
    commandPlaceholder: (command) => `${command}: filter the choices`,
  },
  keys: {
    open: 'Open',
    search: 'Search',
    apply: 'Apply',
    connect: 'Connect',
    newTab: 'New tab',
    move: 'Move',
    back: (segment) => `Remove ${segment}`,
    backShort: 'Back',
    complete: 'Complete',
    stack: 'Narrow to this',
    descend: 'Show choices',
    copyUrl: 'Copy search URL',
    copyUrlShort: 'Copy URL',
    toPanel: 'Advanced search',
  },
  sections: {
    recent: 'Recently opened',
    spaces: 'Spaces',
    commonPages: 'Common pages',
    pagesOf: (project) => `Pages in ${project}`,
    assigned: 'Assigned to me',
    thisIssue: 'This issue',
    results: 'Search results',
    pages: 'Go to',
    projects: 'Projects',
    issues: (prefix) => `Issues starting with ${prefix}`,
    commands: 'Commands',
    learned: 'Most opened first',
    more: (count) => `${count} more`,
    count: (count) => `${count}`,
  },
  rows: {
    searchFor: (query) => `Search for “${query}”`,
    searchSub: (scope) => `Issues, wiki and documents · ${scope}`,
    searching: 'Searching…',
    loading: 'Loading…',
    openDirect: 'Open this issue',
    projectSub: (key) => `Project · ${key}`,
    updatedBy: (person) => `Updated by ${person}`,
    dueOn: (month, day) => `Due ${month}/${day}`,
    overdue: 'Overdue',
    commonPageSub: 'Same in every space',
    personalSettings: 'Personal settings',
    apiKeySettings: 'API key settings',
    spaceSettings: 'Space settings',
    typeHint: 'Type a page name or an issue key',
    assignedFailed: 'Could not load your assigned issues',
    connectThis: 'Connect this space',
    connectSpace: (space) => `${space} is not connected — Connect`,
    authExpired: (space) => `${space} needs to sign in again — Reconnect`,
    rateLimited: (space, seconds) => `${space} is busy — retry in ${seconds}s`,
    offline: 'You are offline. Search resumes when connected',
    pending: (count) => `${count} new results — ↑ to jump to top`,
    noResults: 'No matching results',
    widenTo: (scope) => `Search again in ${scope}`,
    toPanel: 'Refine with advanced search',
    toPanelSub: 'Opens the side panel',
    openExternal: 'Open Backlog issue search',
    openExternalSub: (space) => `Issue search in ${space} · opens in a new tab`,
    moreExternal: (count) => `${count} more in Backlog issue search`,
    copied: (subject) => `Copied ${subject}`,
    searchUrl: 'the search URL',
    copyIssueKey: 'Copy issue key',
    copyIssueUrl: 'Copy issue URL',
    copyIssueTitle: 'Copy key and summary',
    copyIssueMarkdown: 'Copy Markdown link',
    switchSpace: 'Switch space',
    copyIssue: (key) => `Copy ${key}`,
  },
  panel: {
    title: 'Advanced search',
    inputLabel: 'Search',
    placeholder: 'Type and press Enter to search',
    recent: 'Recent',
    filtersLabel: 'Filters',
    singleChoice: 'Pick one',
    clearFilters: 'Clear all filters',
    reconnect: 'Reconnect',
    loading: 'Loading',
    statusLabel: 'Search progress',
    clearFiltersRow: 'Remove active filters',
    fields: {
      space: 'Space',
      project: 'Project',
      type: 'Type',
      status: 'Status',
      assignee: 'Assignee',
      updated: 'Updated',
    },
    options: {
      all: 'All',
      allSpaces: 'All spaces',
      notClosed: 'Not closed',
      me: 'Me',
      unassigned: 'Unassigned',
      anyTime: 'Any time',
      week: 'Past week',
      month: 'Past month',
      quarter: 'Past 3 months',
      issue: 'Issues',
      wiki: 'Wiki',
      document: 'Documents',
    },
    failed: 'Could not load',
    authExpired: 'Signed out',
  },
  connect: {
    title: 'Connect to Backlog Palette',
    inputLabel: 'API key',
    placeholder: 'Paste the API key you issued and connect',
    submit: 'Connect',
    submitting: 'Connecting…',
    doneTitle: (space) => `Connected to ${space}`,
    close: 'Close',
    invalidKey: 'The key is not valid',
    failed: 'Could not connect to this space',
  },
  options: {
    spacesTitle: 'Connected spaces',
    spacesEmpty: 'Press ⌘K on any Backlog page to connect it right there',
    reconnect: 'Reconnect',
    disconnect: 'Remove',
    confirmDisconnect: 'Really remove',
    projects: (count) => `${count} projects`,
    lastSync: (when) => `Last synced ${when}`,
    connected: 'Connected',
    needsReconnect: 'Reconnect needed',
    customDomain: {
      title: 'Add an Enterprise custom domain',
      description: 'Once added, ⌘K also works on Backlog under that domain',
      inputLabel: 'Host name',
      placeholder: 'backlog.example.com',
      add: 'Add',
      invalid: 'That does not look like a valid host name',
      remove: 'Remove',
      empty: 'No custom domains yet',
    },
  },
};
