import type { Labels } from './types';

export const ja: Labels = {
  brand: 'Backlog Palette',
  palette: {
    inputLabel: '検索語',
    placeholder: 'ページ名や課題キーを入力',
    listLabel: '候補',
    escClose: '閉じる',
    escBack: '1 つ前に戻る',
    armedNotice: (segment) => `もう一度で ${segment} を外す`,
    rootScope: 'スペース',
    rootPlaceholder: '移動するスペースを選ぶ',
    commandPlaceholder: '名前で絞り込む',
  },
  keys: {
    open: '開く',
    search: '検索',
    apply: '適用',
    connect: '接続',
    newTab: '新しいタブ',
    move: '移動',
    back: (segment) => `${segment} を外す`,
    backShort: '1 つ戻る',
    complete: '補完',
    stack: 'ここに絞り込む',
    descend: '選択肢を見る',
    copyUrl: '検索 URL をコピー',
    copyUrlShort: 'URL をコピー',
    toPanel: '詳細検索',
  },
  sections: {
    recent: '最近開いた',
    spaces: 'スペース',
    commonPages: '共通のページ',
    pagesOf: (project) => `${project} のページ`,
    assigned: '担当中の課題',
    thisIssue: 'この課題',
    results: '検索結果',
    pages: '移動先',
    projects: 'プロジェクト',
    issues: (prefix) => `${prefix} で始まる課題`,
    commands: 'コマンド',
    learned: 'よく開く順',
    more: (count) => `他 ${count} 件`,
    count: (count) => `${count} 件`,
  },
  rows: {
    searchFor: (query) => `「${query}」を検索`,
    searchSub: (scope) => `課題・Wiki・ドキュメント · ${scope}`,
    searching: '検索中…',
    loading: '読み込み中…',
    openDirect: 'この課題を直接開く',
    projectSub: (key) => `プロジェクト · ${key}`,
    updatedBy: (person) => `最終更新 ${person}`,
    dueOn: (month, day) => `期限 ${month}/${day}`,
    overdue: '期限切れ',
    commonPageSub: 'どのスペースでも同じ',
    personalSettings: '個人設定',
    apiKeySettings: 'API キーの設定',
    spaceSettings: 'スペース設定',
    typeHint: 'ページ名や課題キーを入力してください',
    assignedFailed: '担当中の課題を取得できませんでした',
    assignedOffline: 'オフラインのため担当中の課題を取得できませんでした',
    connectThis: 'このスペースを接続',
    connectSpace: (space) => `${space} は未接続 — 接続する`,
    authExpired: (space) => `${space} は認証が切れています — 再接続`,
    rateLimited: (space, seconds) => `${space} は混み合っています — ${seconds}秒後に再試行`,
    offline: 'オフラインです。接続すると再検索します',
    pending: (count) => `${count} 件の新しい結果 — ↑ で先頭へ`,
    noResults: '一致する結果がありません',
    widenTo: (scope) => `${scope} で検索しなおす`,
    toPanel: '詳細検索で条件を変えて探す',
    toPanelSub: 'サイドパネルを開きます',
    openExternal: 'Backlog の課題検索を開く',
    openExternalSub: (space) => `${space} の課題検索ページ · 新しいタブで開く`,
    moreExternal: (count) => `他 ${count} 件は Backlog の課題検索で`,
    copied: (subject) => `${subject} をコピーしました`,
    searchUrl: '検索 URL',
    copyIssueKey: '課題キーをコピー',
    copyIssueUrl: '課題の URL をコピー',
    copyIssueTitle: '課題キーと件名をコピー',
    copyIssueMarkdown: 'Markdown リンクをコピー',
    switchSpace: 'スペースを切り替え',
    copyIssue: (key) => `${key} をコピー`,
  },
  panel: {
    title: '詳細検索',
    inputLabel: '検索語',
    placeholder: '語を入力して Enter で検索',
    recent: '最近',
    filtersLabel: '絞り込み',
    singleChoice: '1 つだけ選べます',
    clearFilters: '条件をすべて外す',
    reconnect: '再接続',
    loading: '読み込み中',
    statusLabel: '検索の進捗',
    clearFiltersRow: '効いている条件を外す',
    fields: {
      space: 'スペース',
      project: 'プロジェクト',
      type: '種別',
      status: 'ステータス',
      assignee: '担当者',
      updated: '更新日',
    },
    options: {
      all: 'すべて',
      allSpaces: '全スペース',
      notClosed: '完了を除く',
      me: '自分',
      unassigned: '未設定',
      anyTime: '指定なし',
      week: '1 週間以内',
      month: '1 か月以内',
      quarter: '3 か月以内',
      issue: '課題',
      wiki: 'Wiki',
      document: 'ドキュメント',
    },
    failed: '取得できませんでした',
    authExpired: '認証切れ',
  },
  connect: {
    title: 'Backlog Palette に接続',
    inputLabel: 'API キー',
    placeholder: '発行した API キーを貼り付けて接続',
    submit: '接続',
    submitting: '接続中…',
    doneTitle: (space) => `${space} に接続しました`,
    close: '閉じる',
    invalidKey: 'キーが正しくありません',
    failed: 'このスペースに接続できませんでした',
  },
  options: {
    spacesTitle: '接続しているスペース',
    spacesEmpty: 'Backlog のページで ⌘K を押すと、その場で接続できます',
    reconnect: '再接続',
    disconnect: '削除',
    confirmDisconnect: '本当に削除',
    projects: (count) => `${count} プロジェクト`,
    lastSync: (when) => `最終同期 ${when}`,
    connected: '接続済み',
    needsReconnect: '要再接続',
    customDomain: {
      title: 'Enterprise のカスタムドメインを追加',
      description: 'ホストを追加すると、そのドメインの Backlog でも ⌘K が効くようになります',
      inputLabel: 'ホスト名',
      placeholder: 'backlog.example.co.jp',
      add: '追加',
      invalid: 'ホスト名の形式が正しくありません',
      remove: '削除',
      empty: '追加済みのドメインはありません',
    },
  },
};
