import type { Labels } from './types';

export const ja: Labels = {
  brand: 'Backlog Palette',
  palette: {
    inputLabel: '検索語',
    placeholder: 'ページ名や課題キーを入力',
    listLabel: '候補',
    escClose: '閉じる',
    escBack: '1 つ前に戻る',
    armedNotice: 'もう一度 ⌫ で右端を削除',
    rootScope: '全スペース',
  },
  keys: {
    open: '開く',
    search: '検索',
    apply: '適用',
    connect: '接続',
    newTab: '新しいタブ',
    move: '移動',
    back: '右端から 1 段戻す',
    backArmed: (segment) => `${segment} を外す`,
    complete: '補完',
    stack: 'スコープに積む',
    descend: '階層を開く',
    copyUrl: '検索 URL をコピー',
    toPanel: '詳細検索',
  },
  sections: {
    recent: '最近開いた',
    pagesOf: (project) => `${project} のページ`,
    assigned: '担当中の課題',
    results: '検索結果',
    pages: 'ページ',
    commands: 'コマンド',
    learned: '学習で並び替え',
    more: (count) => `他 ${count} 件`,
    loading: (space) => `${space} 読み込み中`,
    countOf: (space, count) => `${space} ${count} 件`,
    summary: (spaces, count) => `${spaces} スペース · ${count} 件`,
  },
  rows: {
    searchFor: (query) => `「${query}」を検索`,
    searchSub: (scope) => `課題・Wiki・ドキュメント · ${scope}`,
    searching: '検索中…',
    openDirect: 'この課題を直接開く',
    recentSub: '最近開いた',
    pageSub: 'ページ',
    typeHint: 'ページ名や課題キーを入力してください',
    connectThis: 'このスペースを接続',
    connectSpace: (space) => `${space} は未接続 — 接続する`,
    authExpired: (space) => `${space} は認証が切れています — 再接続`,
    rateLimited: (space, seconds) => `${space} は混み合っています — ${seconds}秒後に再試行`,
    offline: 'オフラインです。接続すると再検索します',
    pending: (count) => `${count} 件の新しい結果 — ↑ で先頭へ`,
    noResults: '一致する結果がありません',
    widenTo: (scope) => `${scope} で検索しなおす`,
    toPanel: '詳細検索で条件を変えて探す',
    toPanelSub: 'サイドパネルを開きます',
    openExternal: 'Backlog の課題検索を開く',
    moreExternal: (count) => `他 ${count} 件は Backlog の課題検索で`,
    copied: (subject) => `${subject} をコピーしました`,
    copyIssueKey: '課題キーをコピー',
    copyIssueUrl: '課題の URL をコピー',
    copyIssueTitle: '課題キーと件名をコピー',
    copyIssueMarkdown: 'Markdown リンクをコピー',
    switchSpace: 'スペースを切り替え',
  },
  panel: {
    inputLabel: '検索語',
    placeholder: '語を入力して Enter で検索',
    recent: '最近',
    filtersLabel: '絞り込み',
    singleChoice: '1 つだけ選べます',
    clearFilters: '条件をすべて外す',
    reconnect: '再接続',
    loading: '読み込み中',
    statusLabel: '検索の進捗',
    clearFiltersRow: '効いている条件を外す',
    fields: {
      space: 'スペース',
      project: 'プロジェクト',
      type: '種別',
      status: 'ステータス',
      assignee: '担当者',
      updated: '更新日',
    },
    options: {
      all: 'すべて',
      allSpaces: '全スペース',
      notClosed: '完了を除く',
      me: '自分',
      unassigned: '未設定',
      anyTime: '指定なし',
      week: '1 週間以内',
      month: '1 か月以内',
      quarter: '3 か月以内',
      issue: '課題',
      wiki: 'Wiki',
      document: 'ドキュメント',
    },
    authExpired: '認証切れ',
  },
  connect: {
    title: 'Backlog Palette に接続',
    steps: [
      'このページで API キーを発行します（メモ欄に Backlog Palette と入っています）',
      '表示されたキーをコピーして下に貼り付け、接続を押します',
    ],
    inputLabel: 'API キー',
    placeholder: 'API キーを貼り付け',
    submit: '接続',
    submitting: '接続中…',
    note: 'キーは端末内にのみ保存され、外部へは送信されません',
    oauth: 'OAuth で接続',
    doneTitle: (space) => `${space} に接続しました`,
    doneHint: '⌘K でこのスペースを検索できます',
    close: '閉じる',
    invalidKey: 'キーが正しくありません',
  },
  options: {
    spacesTitle: '接続しているスペース',
    spacesEmpty: 'Backlog のページで ⌘K を押すと、その場で接続できます',
    reconnect: '再接続',
    disconnect: '削除',
    confirmDisconnect: '本当に削除',
    projects: (count) => `${count} プロジェクト`,
    lastSync: (when) => `最終同期 ${when}`,
    connected: '接続済み',
    needsReconnect: '要再接続',
    method: { apiKey: 'API キー', oauth: 'OAuth' },
    customDomain: {
      title: 'Enterprise のカスタムドメインを追加',
      description: 'ホストを追加すると、そのドメインの Backlog でも ⌘K が効くようになります',
      inputLabel: 'ホスト名',
      placeholder: 'backlog.example.co.jp',
      add: '追加',
      invalid: 'ホスト名の形式が正しくありません',
      remove: '削除',
      empty: '追加済みのドメインはありません',
    },
  },
};
